development:
  adapter: postgresql
  encoding: unicode
  database: dev-stackcommerce
  pool: 5
  username: stackcommerce
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: test-stackcommerce
  pool: 5
  username: stackcommerce
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: d33qid4b9d14r5
  pool: 5
  username: zsdxghkuztpcic
  password: <%= Rails.application.secrets.db_password %>
